name: Build Minimal Custom ISO

on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Minimal Arch ISO
        uses: archlinux/archiso-action@v1
        with:
          profile: releng
          custom-packages: >
            xorg-server
            openbox
            lightdm
            lightdm-gtk-greeter
            firefox
            bluez
            bluez-utils
            blueman
            waydroid
            curl

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Custom-Minimal-Linux-ISO
          path: output/*.iso
